# Generated by Django 5.1 on 2024-09-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_alter_itemcarrito_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
